In [2]:
#Importando a biblioteca
import numpy as np

In [3]:
quantidade_produtos = [10,5,3,8] #Lista
custo_produtos = [5,10,2,3] #Lista

array_quantidade = np.array(quantidade_produtos) #Array
array_custo = np.array(custo_produtos)

faturamento = array_quantidade * array_custo
print(faturamento)

print(type(faturamento))



[50 50  6 24]
<class 'numpy.ndarray'>


In [4]:
#Gerar um array automatico
np.arange(10,20,2) #Sobe de dois em dois

array([10, 12, 14, 16, 18])

Criar duas listas:

- 5 produtos (apenas inserir valores).
- A primeira lista, custo do produto.
- A segunda lista, o preço de venda.
- Desafio: Calcular o lucro de cada produto.

In [5]:
custo_produtos = [50,100,150,200,250]
preco_venda = [100,200,300,400,500]

array_custo = np.array(custo_produtos)
array_preco = np.array(preco_venda)

lucro_produto = array_preco - array_custo
print(lucro_produto)
print(type(lucro_produto))


[ 50 100 150 200 250]
<class 'numpy.ndarray'>


In [6]:
salarios = np.array([2,3,4,5,6,500])
maior_salario = np.max(salarios)
print(maior_salario)


500


In [7]:
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")


86.67


In [8]:
menor_salario = np.min(salarios)
print(menor_salario)


2


In [9]:
mediana_salarios = np.median(salarios)
print(mediana_salarios)

4.5


In [10]:
desvio = np.std(salarios)
print(desvio)

184.852794286577


Criar uma lista de vendas por dia:

vendas = [10,20,45,5,90]

- Exibir a maoir vénda
- Exibir a menor venda
- Exibir a média de vendas
-Exibir a mediana de vendas


In [11]:
vendas = np.array([10,20,45,5,90])
maior_venda = np.max(vendas)
print(maior_venda)


90


In [12]:
vendas = np.array([10,20,45,5,50])
menor_venda = min(vendas)
print(menor_venda)

5


In [14]:
vendas = np.array([10,20,45,5,90])
media_venda = np.median(vendas)
print(media_venda)

20.0
